#!/bin/bash

pushd .

pip install -r requirements.txt \
    && pip install -r test_requirements.txt \
    && pip install -r doc/doc_requirements.txt \
    && python setup.py develop \
    && cd ../BiblioPixelAnimations \
    && python setup.py develop

# TODO: the last two lines are janky - they are required because of a bug in
# BiblioPixelAnimations's setup.py, but they won't work on every system.  We
# should fix that bug and then remove the last two lines

popd
